In [2]:
#sec3.1
round(1236.12481348515, 2)

1236.12

In [3]:
#sec3.1
a = 9761973469.3235356
round(a , -2)

9761973500.0

In [6]:
#sec3.2
from decimal import Decimal
a = Decimal('24593.65')
b = Decimal('34535.694')
print(round(a + b, 1))


59129.3


In [12]:
#sec3.3 Formatting Numbers for Output
b = 2589.34587
format(b, '>6.3f') 

'2589.346'

In [13]:
#sec3.4
a = 7923648
b = 235834
format(a * b, 'x')


'1b315264180'

In [17]:
#sec3.5
data = b'd6 c6 07 43 3d 69 5c a1 e9 21 d5 08 35 ac 91 dd'
int.from_bytes(data, 'big')


60249808541635175465051241409286940860194848435975673838813666715207852666479032798801559828780010649883181605988

In [18]:
#sec3.5
len(data) 


47

In [20]:
#sec3.5
data = 60249808541635175465051241409286940860194848435975673838813666715207852666479032798801559828780010649883181605988
data.to_bytes(47, 'big')

b'd6 c6 07 43 3d 69 5c a1 e9 21 d5 08 35 ac 91 dd'

In [21]:
#sec3.6
a = complex(6 , 7)
b = complex (8, 9)
c = a * b
print(c)

(-15+110j)


In [22]:
#sec3.7
a = float('inf')
b = float('nan')
c = a + b
print(c)


nan


In [25]:
#sec3.8
from fractions import Fraction

a = Fraction (2, 3)
b = Fraction (5, 6)
c = a + b
float(c)


1.5

In [28]:
#sec3.9
import numpy as np

aa = np.array([12, 56, 13])
ab = np.array([78, 34, 70])
ac = (aa + ab)/2
print(ac)

[45.  45.  41.5]


In [33]:
#sec3.10
import numpy as np

m = np.matrix([[12, 45, 3.9], [11, -98, 6.9]])

def f(x):
    return x*2

f(m)


matrix([[  24. ,   90. ,    7.8],
        [  22. , -196. ,   13.8]])

In [34]:
#sec3.11
import random

m = np.matrix([[12, 45, 3.9], [11, -98, 6.9]])

random.choice(m)

matrix([[12. , 45. ,  3.9]])

In [41]:
#sec3.11
import random

data = random.getrandbits(36)
data.to_bytes(36, 'big')




b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0ee\xc9\x17y'

In [38]:
import random

random.uniform(10.5, 11)

10.86454919867452