###4.1 The NumPy ndarray: A Multidimesional Array Object

In [1]:
import numpy as np

In [2]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [3]:
#write mathematical operations with data

data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [4]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [5]:
#find dimension(shape) of data

data.shape

(2, 3)

In [7]:
#find data type of 'data'

data.dtype

dtype('float64')

In [8]:
#Creating ndarrays

data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
#Nested sequences will be converted into a multidimensional array

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2= np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#finding data tupe of ndarray

arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

In [13]:
#Inspecting with (ndim) and (shape)

arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [15]:
#numpy.zeros --create array of zeros// numpy.ones --create array of ones

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#numpy.empty creates an array without initializing values to any particular value

np.empty((2,3,3))

array([[[1.37962049e-306, 1.24610791e-306, 1.11260959e-306],
        [1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
        [1.78019082e-306, 4.45061456e-308, 1.24612081e-306]],

       [[1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
        [1.78019625e-306, 1.11255866e-306, 8.90098127e-307],
        [9.34609790e-307, 3.91792279e-317, 1.24610587e-306]]])

In [21]:
#numpy.arange is an array-valued version of the built-in Python 'range' function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#setting datatypes

arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [22]:
#explicitly convert or cast an array from one data type to another using 'astype'

arr3 = np.array([7,8,9,10])

arr3.dtype

dtype('int32')

In [24]:
float_arr3 = arr3.astype(np.float64)
float_arr3

array([ 7.,  8.,  9., 10.])

In [26]:
float_arr3.dtype

dtype('float64')

In [27]:
#If you have an array of strings representing numbers, you can use astype to convert them to numeric form

numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [28]:
#Arithmetic with NumPy Arrays

arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
#Comparisons between arrays of the same size yield Boolean arrays

arr3 > arr2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
#Basic Indexing and Slicing

arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5:8]

array([5, 6, 7])

In [39]:
arr[5:8] = 100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [40]:
arr_slice = arr[5:8]
arr_slice

array([100, 100, 100])

In [41]:
arr_slice[0] = 99
arr

array([  0,   1,   2,   3,   4,  99, 100, 100,   8,   9])

In [42]:
#Boolean Indexing

names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

data = np.array(
    [[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]]
)

In [43]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [44]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [45]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [46]:
#The Boolean array must be of the same length as the array axis it’s indexing

data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [ ]:
#Fancy Indexing